services:
  mysql_ventas:
    image: mysql:8
    container_name: mysql_ventas
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ventas_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_ventas_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  mysql_despacho:
    image: mysql:8
    container_name: mysql_despacho
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: despacho_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - mysql_despacho_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  backend_ventas:
    build:
      context: ./back-Ventas_SpringBoot/Springboot-API-REST
      dockerfile: Dockerfile
    container_name: backend_ventas
    restart: always
    depends_on:
      - mysql_ventas
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_ventas:3306/ventas_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - app_network

  backend_despacho:
    build:
      context: ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
      dockerfile: Dockerfile
    container_name: backend_despacho
    restart: always
    depends_on:
      - mysql_despacho
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_despacho:3306/despacho_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - app_network

  frontend:
    build:
      context: ./front_despacho
      dockerfile: Dockerfile
    container_name: front_despacho
    restart: always
    ports:
      - "3000:80"
    networks:
      - app_network

volumes:
  mysql_ventas_data:
  mysql_despacho_data:

networks:
  app_network:
    driver: bridge
