apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-despacho-pvc
  namespace: proyecto-semestral
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-despacho
  namespace: proyecto-semestral
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mysql-despacho
  template:
    metadata:
      labels:
        app: mysql-despacho
    spec:
      containers:
        - name: mysql-despacho
          image: mysql:8
          args: ["--default-authentication-plugin=mysql_native_password"]
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
            - name: MYSQL_DATABASE
              value: "despacho_db"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              value: "root"
          volumeMounts:
            - name: mysql-despacho-storage
              mountPath: /var/lib/mysql
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 30
            periodSeconds: 15
      volumes:
        - name: mysql-despacho-storage
          persistentVolumeClaim:
            claimName: mysql-despacho-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-despacho
  namespace: proyecto-semestral
spec:
  selector:
    app: mysql-despacho
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP
