apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-despacho
  namespace: proyecto-semestral
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-despacho
  template:
    metadata:
      labels:
        app: backend-despacho
    spec:
      containers:
        - name: backend-despacho
          image: REPLACE_ECR_BACKEND_DESPACHO:REPLACE_TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-despacho:3306/despacho_db?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "root"
          resources:
            requests:
              cpu: "200m"
              memory: "384Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 40
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: backend-despacho
  namespace: proyecto-semestral
spec:
  selector:
    app: backend-despacho
  ports:
    - port: 8081
      targetPort: 8081
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-despacho-hpa
  namespace: proyecto-semestral
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-despacho
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
